// <auto-generated />
using System;
using DOService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DOService.Migrations
{
    [DbContext(typeof(DOServiceContext))]
    [Migration("20210810172811_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DOService.Models.DoiHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ApprovedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("approved_date");

                    b.Property<bool>("ApprovedFlag")
                        .HasColumnType("boolean")
                        .HasColumnName("approved_flag");

                    b.Property<string>("ApprovedUserId")
                        .HasColumnType("text")
                        .HasColumnName("approved_user_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.ToTable("doi_headers");
                });

            modelBuilder.Entity("DOService.Models.DoiOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BurdenGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DoiHeaderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveFromDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EffectiveToDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InterestType")
                        .HasColumnType("text");

                    b.Property<decimal>("NriDecimal")
                        .HasColumnType("numeric");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text");

                    b.Property<string>("PayCode")
                        .HasColumnType("text");

                    b.Property<string>("SuspenseReason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("doi_owners");
                });
#pragma warning restore 612, 618
        }
    }
}
